mod friendslist;
mod group;
mod groupslist;
mod help;
mod home_page;
mod login;
mod messages;
mod register;
mod settings;
mod user;

pub use friendslist::FriendlistPage;
pub use group::GroupPage;
pub use groupslist::GroupslistPage;
pub use help::HelpPage;
pub use home_page::HomePage;
pub use login::LoginPage;
pub use messages::MessagesPage;
pub use register::RegisterPage;
pub use user::UserPage;
